// GENERATED by export-schema — do not edit. (S3-R42)
class IdeaCaptured { const IdeaCaptured(); }
class VoiceTranscript { const VoiceTranscript(); }
class WikiEdit { const WikiEdit(); }
class RecallResult { const RecallResult(); }
class AgentMessage { const AgentMessage(); }
class DreamTurn { const DreamTurn(); }
class Reasoning { const Reasoning(); }
class ErrorItem { const ErrorItem(); }
