// QCue REC-R7/REC-R8: recall history models. ConversationSummary backs the history drawer rows;
// ConversationMessage backs a reopened thread's prior turns. Mirrors protocol::ConversationSummary /
// protocol::ConversationMessage (the wire DTOs regenerated by export-schema).
import 'package:flutter/foundation.dart';

/// One row in the recall history drawer (`GET /v1/conversations`).
@immutable
class ConversationSummary {
  const ConversationSummary({
    required this.id,
    required this.title,
    required this.updatedAt,
    this.lastSnippet,
  });

  final String id;
  final String title;
  final String updatedAt; // RFC3339 UTC; formatted locally by the UI
  final String? lastSnippet;

  factory ConversationSummary.fromJson(Map<String, dynamic> j) => ConversationSummary(
        id: j['id'] as String,
        title: j['title'] as String? ?? '',
        updatedAt: j['updated_at'] as String? ?? '',
        lastSnippet: j['last_snippet'] as String?,
      );
}

/// One persisted turn in a reopened thread (`GET /v1/conversations/{thread}/messages`).
@immutable
class ConversationMessage {
  const ConversationMessage({required this.role, required this.content});

  final String role; // "user" | "assistant"
  final String content;

  factory ConversationMessage.fromJson(Map<String, dynamic> j) => ConversationMessage(
        role: j['role'] as String? ?? '',
        content: j['content'] as String? ?? '',
      );
}
